# Generated by Django 5.2.3 on 2025-11-29 17:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="first_visit",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="visitor",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
