# Generated by Django 5.2.3 on 2025-11-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_visitor_first_visit_alter_visitor_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="visitor",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
